# Generated by Django 6.0.5 on 2026-09-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_5', '0003_penalty_alter_car_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('website_url', models.URLField(verbose_name='Сайт компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Компании-партнеры',
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники (Контакты)'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос/Термин', 'verbose_name_plural': 'Словарь терминов (FAQ)'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод/Купон', 'verbose_name_plural': 'Промокоды и купоны'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, default='', verbose_name='Сертификат (текст)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, default='', verbose_name='Реквизиты компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='company/', verbose_name='Видео о компании (файл)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='Видео о компании (URL)'),
        ),
    ]
